services:
  app:
    image: ghcr.io/imigueldiaz/zephyr-md:v0.1.2-alpha
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8585:3000"
    volumes:
      - ./content:/app/content
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
