services:
  app:
    image: ghcr.io/imigueldiaz/zephyr-md:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "8585:8585"
    volumes:
      - ./content:/app/content
      - ./public:/app/public
      - ./templates:/app/templates
    environment:
      - NODE_ENV=production
      - PORT=8585
      # Auth environment variables
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
    env_file:
      - .env
    restart: unless-stopped
