services:
  app:
    image: ghcr.io/imigueldiaz/zephyr-md:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "8585:8585"
    volumes:
      - ./content:/app/content
      - ./public:/app/public
      - ./templates:/app/templates
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=8585
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8585/ || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
