services:
  app:
    image: ghcr.io/imigueldiaz/zephyr-md:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8585:8585"
    volumes:
      - ./content:/app/content
      - ./public:/app/public
      - ./templates:/app/templates
    environment:
      - NODE_ENV=production
      - PORT=8585
    restart: unless-stopped
